name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Erlang ${{matrix.otp-version}} / Elixir ${{matrix.elixir-version}}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # https://hexdocs.pm/elixir/compatibility-and-deprecations.html
        elixir-version: [1.17.x, 1.16.x, 1.15.x, 1.14.x, 1.13.x]
        include:
          - elixir-version: 1.17.x
            otp-version: 25.x
          - elixir-version: 1.16.x
            otp-version: 25.x
          - elixir-version: 1.15.x
            otp-version: 25.x
          - elixir-version: 1.14.x
            otp-version: 25.x
          - elixir-version: 1.13.x
            otp-version: 24.x
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - run: make dependencies
      - run: make lint
      - run: make test
      - run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mix hex.publish --dry-run
        env:
          HEX_API_KEY: DRYRUN
