name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.MIREGO_HEXPM_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.x
          elixir-version: 1.17.x
      - run: mix deps.get
      - run: mix compile --docs
      - run: mix hex.publish --yes
